import React from 'react'
import Hero from './component/home-sections/HeroSection'
import About from './component/home-sections/About';

export const metadata = {
  title: "home page",
  description: "generated by create next app",
};


export default function page() {
  return (
    <>
      <Hero />
      <About />
    </>
  )
}
